### ISSUE TITLE
Translate Channels, Channel Buffering, Channel Synchronization, Channel Directions, Select

### ISSUE THREAD

**Issue by benhaq** [s6k-gopher/gobyexample-vn#3]
1. [channels](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/channels)
2. [channel-buffering](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/channel-buffering)
3. [channel-directions](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/channel-directions)
4. [channel-synchronization](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/channel-synchronization)
5. [select](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/select)

**Comment by lyxuansang91** [comment]
PR #8
