### ISSUE TITLE
Translate Stateful Goroutines, Sorting, Sorting by Functions, Panic, Defer

### ISSUE THREAD

**Issue by benhaq** [s6k-gopher/gobyexample-vn#9]
1. [stateful-goroutines](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/stateful-goroutines)
2. [sorting](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/sorting)
3. [sorting-by-functions](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/sorting-by-functions)
4. [panic](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/panic)
5. [defer](https://github.com/s6k-gopher/gobyexample-vn/blob/main/public/defer)

**Comment by lyxuansang91** [comment]
link to #22
